import Head from 'next/head'
import TrailerHome from '../components/Home/TrailerHome'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>PELIS-API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="img/favicon.png" />
        <link rel="stylesheet" href="../styles/Home.module.css" />
      </Head>

      <TrailerHome />


      <style jsx>{`
        h1{
            color:#fff
          }
      `}</style>
    </div>
  )
}
