import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>PELIS-API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="img/favicon.png" />
      </Head>
<h1>Hola</h1>
<h1>Hola</h1>
<h1>Hola</h1>
<h1>Hola</h1>
<h1>Hola</h1>
<h1>Hola</h1>
<h1>Hola</h1><h1>Hola</h1>
<h1>Hola</h1>
<h1>Hola</h1>
<h1>Hola</h1>

<h1>Hola</h1>
<h1>Hola</h1>
<h1>Hola</h1>
<h1>Hola</h1>
<h1>Hola</h1>

<h1>Hola</h1>
<h1>Hola</h1>

<h1>Hola</h1>
<h1>Hola</h1><h1>Hola</h1>

<h1>Hola</h1>
<h1>Hola</h1>


<h1>Hola</h1>
<h1>Hola</h1>
<h1>Hola</h1>
<h1>Hola</h1>
<h1>Hola</h1>
<h1>Hola</h1>
<style jsx>{`
h1{
  color:#fff
}
`}</style>
    </div>
  )
}
